const PLAYER_HEALTH = 100;
const PLAYER_SPEED = 5;

const ZOMBIE_HEALTH_BASE = 50;
const ZOMBIE_SPEED_BASE = 2;
const ZOMBIE_DAMAGE_BASE = 10;

const KATANA_DAMAGE = 25;
const KATANA_ATTACK_SPEED = 1.5;

const BARE_HANDS_DAMAGE = 10;
const BARE_HANDS_ATTACK_SPEED = 2;

const WIZARD_BOOK_DAMAGE = 20;
const WIZARD_BOOK_BURN_DURATION = 3;

const DUAL_GUN_DAMAGE = 15;
const DUAL_GUN_EXPLOSIVE_RADIUS = 50;

const INITIAL_ZOMBIE_COUNT = 5;
const ZOMBIE_COUNT_INCREMENT = 2;

const POINTS_PER_ZOMBIE = 100;
const POINTS_INCREMENT_PER_WAVE = 50;

const GAME_WIDTH = 800;
const GAME_HEIGHT = 600;

const TILE_SIZE = 32;

export {
    PLAYER_HEALTH,
    PLAYER_SPEED,
    ZOMBIE_HEALTH_BASE,
    ZOMBIE_SPEED_BASE,
    ZOMBIE_DAMAGE_BASE,
    KATANA_DAMAGE,
    KATANA_ATTACK_SPEED,
    BARE_HANDS_DAMAGE,
    BARE_HANDS_ATTACK_SPEED,
    WIZARD_BOOK_DAMAGE,
    WIZARD_BOOK_BURN_DURATION,
    DUAL_GUN_DAMAGE,
    DUAL_GUN_EXPLOSIVE_RADIUS,
    INITIAL_ZOMBIE_COUNT,
    ZOMBIE_COUNT_INCREMENT,
    POINTS_PER_ZOMBIE,
    POINTS_INCREMENT_PER_WAVE,
    GAME_WIDTH,
    GAME_HEIGHT,
    TILE_SIZE
};